### ISSUE TITLE
Clicking arrows no longer works (solution included)

### ISSUE THREAD

**Issue by EinarW** [Spynder/WaniMaru#1]
Upon clicking an arrow, the console throws the following error, and nothing happens in the UI.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at HTMLDocument.checkItemClicks (canvasControl.js:262:17)
checkItemClicks @ canvasControl.js:262`

![image](https://github.com/Spynder/WaniMaru/assets/26111260/d540a1ec-d440-4d69-8bff-d661a4611e6e)

Tested in Chrome Version 120.0.6099.131 (Official Build) (64-bit)

##
Debugging reveals that `event.path`, in `checkItemClicks(event)` is undefined.

![image](https://github.com/Spynder/WaniMaru/assets/26111260/266c6e4b-4e6a-481a-9bc9-27c3f77be183)

The `path` property of Event is a non-standard property, and may no longer be supported. The standard equivalent property is `composedPath` ([StackOverflow](https://stackoverflow.com/questions/39245488/event-path-is-undefined-running-in-firefox)).

### Solution

Replacing `event.path` on line 262 in canvasControl.js with `event.composedPath()` will solve the issue:
`if(event.composedPath().findIndex(el => el.id == "info" || el.id == "apiModal") !== -1) return; // If clicked on info or modal is on don't propagate`

**Comment by Spynder** [comment]
Hey there! Sorry for totally missing that opened issue, just found it now. I've implemented the fix you proposed, so it should all probably work now.
Again, sorry for missing, and thanks for telling me about this issue (and how to fix it as well!)
